name: tests
on: [push, pull_request]
jobs:
  tests:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install package and dependencies
        run: pip install .[test]
      - name: Run the tests
        run: tox -e py
      - name: Upload coverage
        uses: codecov/codecov-action@v1
